language: node_js
node_js:
  - "6.0"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
  artifacts:
    debug: true
    paths:
      - $TRAVIS_BUILD_DIR/backstop_data/
cache:
  yarn: true
